#!/usr/bin/env bash

getSyntax() {
    case "${fileExt}" in
        txt)                    lang="text"             ;;
        htm|html|html5)         lang="html5"            ;;
        css)                    lang="css"              ;;
        js)                     lang="javascript"       ;;
        php|php3|php4)          lang="php"              ;;
        py)                     lang="python"           ;;
        rb)                     lang="ruby"             ;;
        bash|sh)                lang="bash"             ;;
        nix)                    lang="bash"             ;;
        erl|hrl)                lang="erlang"           ;;
        go)                     lang="go"               ;;
        c)                      lang="c"                ;;
        cpp)                    lang="cpp"              ;;
        diff)                   lang="diff"             ;;
        tex)                    lang="latex"            ;;
        sql)                    lang="sql"              ;;
        xml)                    lang="xml"              ;;
    esac
}


if [[ $# -ge 1 && -f "$1" ]]; then
    data="text@${1}"
    fileExt="${1##*.}"
    getSyntax
else
    data="text@-"
fi

echo ""
echo "Enter expiration. Use m for minutes, h for hours and d for days"
read -p "Set '0' for no expiration. Examples: 10m -> 10 Minutes, 3d -> 3 days:  " </dev/tty
echo # Just to move to a new line

expiration="${REPLY}"
timeframe="${expiration: -1}"
duration="${expiration:0:-1}"
case "${timeframe}" in
    0) expire=0 ;;
    m) expire=$((duration)) ;;
    h) expire=$((duration * 60)) ;;
    d) expire=$((duration * 60 * 24)) ;;
    *) echo "No valid expiration give. Try again."; exit ;;
esac

if [[ -z "${lang}" ]]; then
    echo ""
    echo "Enter language for syntax highlighting."
    read -p "Examples: text, bash, html5, php, javascript, c, cpp, lua, python, ruby, xml:  " </dev/tty
    echo # Just to move to a new line

    lang="${REPLY}"
    if [[ -z "${lang}" ]]; then
        lang="text"
    fi
fi

curl -d "expire=${expire}" -d "lang=${lang}" --data-urlencode "${data}" "https://paste.simplylinux.ch/api/create?apikey=isiengie0ohqua7dee2leibooGh1ai"
